In [2]:
import pandas as pd

In [4]:
# Subject: very high + high

base_dir = 'your_path'
data1 = pd.read_csv(base_dir + 'laf_eeg_data_9ch_360000.csv')
data2 = pd.read_csv(base_dir + 'laf_eeg_data2_9ch_240000.csv')

In [5]:
# 데이터 합치기
data = pd.concat([data1, data2], axis=0)

In [6]:
data

,FC3,FCz,FC4,C3,Cz,C4,CP3,CPz,CP4,label
0,0.004885,0.021394,-0.004997,0.000477,0.018715,-0.030185,-0.011860,-0.028419,0.034432,3
1,0.000437,0.017261,-0.002674,0.003289,0.015006,-0.031561,-0.010945,-0.024649,0.040919,3
2,0.004613,0.014660,-0.000274,0.000667,0.010949,-0.031562,-0.008879,-0.019565,0.041101,3
3,0.016540,0.013472,0.004274,-0.003721,0.007394,-0.029907,-0.006108,-0.018176,0.032596,3
4,0.023611,0.014114,0.004756,-0.004507,0.003148,-0.023453,-0.000821,-0.024775,0.025822,3
...,...,...,...,...,...,...,...,...,...,...
239995,0.043431,0.024130,0.029494,-0.009207,-0.027949,-0.049328,-0.040003,0.009066,0.073364,2
239996,0.034528,0.030303,0.035609,-0.009888,-0.026360,-0.049572,-0.023452,0.000818,0.060455,2
239997,0.026627,0.035436,0.041257,-0.012342,-0.026241,-0.051329,0.000513,-0.006272,0.047633,2
239998,0.017483,0.037924,0.047005,-0.014076,-0.030238,-0.049147,0.025322,-0.008785,0.032778,2
239999,0.003724,0.035337,0.062659,-0.012908,-0.033988,-0.042228,0.040724,-0.007446,0.010620,2

In [7]:
data.to_csv(base_dir + 'laf_eeg_data_9ch_600000.csv', index=False)

In [8]:
# Subject: very high + high + fair

base_dir = '/Users/imdohyeon/Library/CloudStorage/GoogleDrive-dhlim1598@gmail.com/공유 드라이브/4N_PKNU/Project/EEG-LLM/Dataset/subj(high+inter+low)/'
data1 = pd.read_csv(base_dir + 'laf_eeg_data_9ch_360000.csv')
data2 = pd.read_csv(base_dir + 'laf_eeg_data2_9ch_240000.csv')
data3 = pd.read_csv(base_dir + 'laf_eeg_data3_9ch_240000.csv')

In [9]:
data = pd.concat([data1, data2, data3], axis=0)

In [10]:
data

,FC3,FCz,FC4,C3,Cz,C4,CP3,CPz,CP4,label
0,0.004885,0.021394,-0.004997,0.000477,0.018715,-0.030185,-0.011860,-0.028419,0.034432,3
1,0.000437,0.017261,-0.002674,0.003289,0.015006,-0.031561,-0.010945,-0.024649,0.040919,3
2,0.004613,0.014660,-0.000274,0.000667,0.010949,-0.031562,-0.008879,-0.019565,0.041101,3
3,0.016540,0.013472,0.004274,-0.003721,0.007394,-0.029907,-0.006108,-0.018176,0.032596,3
4,0.023611,0.014114,0.004756,-0.004507,0.003148,-0.023453,-0.000821,-0.024775,0.025822,3
...,...,...,...,...,...,...,...,...,...,...
239995,-0.029551,0.023615,-0.018839,0.004575,0.023919,-0.014516,-0.018566,-0.004741,0.014152,2
239996,-0.028830,0.023304,-0.018926,0.005345,0.024892,-0.013452,-0.020600,-0.008209,0.015543,2
239997,-0.029110,0.022831,-0.019267,0.004893,0.027360,-0.012168,-0.020882,-0.011858,0.015728,2
239998,-0.030903,0.025107,-0.021943,0.004109,0.029337,-0.010909,-0.020409,-0.014264,0.015358,2
239999,-0.034116,0.028762,-0.025682,0.004595,0.029957,-0.009851,-0.018917,-0.016094,0.014706,2

In [11]:
data.to_csv(base_dir + 'laf_eeg_data_9ch_840000.csv', index=False)